standalone_tags:
  [
    {id: 0, size: 0.040},
    {id: 1, size: 0.040},
    {id: 2, size: 0.040},
    {id: 3, size: 0.040},
    {id: 4, size: 0.040},
    {id: 5, size: 0.040},
    {id: 6, size: 0.040},
    {id: 7, size: 0.040},
    {id: 8, size: 0.040},
    {id: 9, size: 0.040},
    {id: 10, size: 0.040},
    {id: 11, size: 0.040},
    {id: 12, size: 0.040},
    {id: 13, size: 0.040},
    {id: 14, size: 0.040},
    {id: 15, size: 0.040},
    {id: 16, size: 0.040},
    {id: 17, size: 0.040},
    {id: 18, size: 0.040},
    {id: 19, size: 0.040},
    {id: 20, size: 0.040},
    {id: 21, size: 0.040},
    {id: 22, size: 0.040},
    {id: 23, size: 0.040},
    {id: 24, size: 0.040},
    {id: 25, size: 0.040},
    {id: 26, size: 0.040},
    {id: 27, size: 0.040},
    {id: 28, size: 0.040},
    {id: 29, size: 0.040},
  ]
tag_bundles:
  []
